#-----------------------------------------------------------------------------------------------------------------------
#   Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
#  with the License. A copy of the License is located at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
#  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
#  and limitations under the License.
#-----------------------------------------------------------------------------------------------------------------------
aws:
  accountId:
  region:
  s3:
    bucket:
    prefix: "commands/"
    roleArn:
  iot:
    endpoint:
  jobs:
    maxTargets: 100

tmpdir: "/tmp"

tables:
  templates: cdf-commands-templates
  jobs: cdf-commands-jobs

mqtt:
  topics:
    presigned: cdf/commands/presignedurl/{commandId}/{thingName}/{direction}

cors:
  origin:
  exposedHeaders: content-type,location

templates:
  addThingToGroup: add_thing_to_group

assetLibrary:
  mode: lambda
  apiFunctionName:
provisioning:
  mode: lambda
  apiFunctionName:

supportedApiVersions:
  - json:
      - '1.0'

logging:
  level: debug

customDomain:
  basePath:
