#--------------------------------------------------------------------------------
#   Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#                                                                                                                    
#  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance    
#  with the License. A copy of the License is located at                                                             
#                                                                                                                    
#      http://www.apache.org/licenses/LICENSE-2.0                                                                    
#                                                                                                                    
#  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES 
#  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions    
#  and limitations under the License.                                                                                
#---------------------------------------------------------------------------------
aws:
  accountid: AWS_ACCOUNT_ID
  region: AWS_REGION
assetLibrary:
  baseUrl: CDF_ASSETLIBRARY_BASEURL
assetLibraryHistory:
  baseUrl: CDF_ASSETLIBRARYHISTORY_BASEURL
commands:
  baseUrl: CDF_COMMANDS_BASEURL
greengrassProvisioning:
  baseUrl: CDF_GREENGRASSPROVISIONING_BASEURL
provisioning:
  baseUrl: CDF_PROVISIONING_BASEURL
  templates:
    bucket: CDF_PROVISIONING_TEMPLATES_BUCKET
    prefix: CDF_PROVISIONING_TEMPLATES_PREFIX
    suffix: CDF_PROVISIONING_TEMPLATES_PREFIX
greengrassDeployment:
  baseUrl: CDF_GREENGRASS_DEPLOYMENT_BASEURL

thing:
  name: CDF_THING_NAME 
  arn: CDF_THING_ARN

logging:
  level: CDF_LOGGING_LEVEL
